name: fitdrills
favicon: null
layout_spectrum: 0.6967752871569246
typography_spectrum: 0.771079576574266
title: FIT DRILLS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6268418389372528
  lightness: 0.9760490448679775
  saturation: 0.24037334672175348
  rhythmicContrast: 0.17036343971267343
purpose: []
